export interface RatingRange {
    id: string;
    min: number;
    max: number;
    label: string;
    color: string;
}

export type MeterSkin = 'pastel' | 'neon' | 'retro' | 'minimal' | 'cyber';

export type Language = 'en' | 'zh' | 'hi' | 'es' | 'ar' | 'bn' | 'pt' | 'ru' | 'ja' | 'tr' | 'fr' | 'de' | 'ko' | 'vi' | 'it' | 'fa' | 'pl' | 'uk' | 'nl' | 'th';

export type NeedleType = 'arrow' | 'classic' | 'modern' | 'thin' | 'bold';

export type CenterIcon = 'heart' | 'star' | 'circle' | 'diamond' | 'none';

export type FontFamily =
    | 'Inter' | 'Roboto' | 'Poppins' | 'Open Sans' | 'Lato'
    | 'Montserrat' | 'Oswald' | 'Source Sans 3' | 'Raleway' | 'PT Sans'
    | 'Merriweather' | 'Nunito' | 'Playfair Display' | 'Ubuntu' | 'Mukta'
    | 'Quicksand' | 'Kanit' | 'Noto Sans' | 'Rubik' | 'Bebas Neue'
    | 'Anton' | 'Josefin Sans' | 'Pacifico' | 'Shadows Into Light'
    | 'Comic Sans MS' | 'Courier New' | 'Georgia';

export type FontEffect = 'none' | 'shadow' | 'outline' | 'glow' | 'emboss';

export type MeterShape = 'gauge' | 'tube';

export interface MeterSettings {
    title: string;
    scoreValue: number;
    maxScore: number;
    theme: 'light' | 'dark';
    skin: MeterSkin;
    backgroundColor: string;
    language: Language;
    // Advanced customization options
    needleType: NeedleType;
    centerIcon: CenterIcon;
    fontFamily: FontFamily;
    fontSize: number;
    fontEffect: FontEffect;
    needleColor: string;
    meterShape: MeterShape;
    // Title customization
    titleFontSize?: number;
    titleVisible?: boolean;
    titleColor?: string;
    titlePositionY?: number;
}

export interface TranslationUI {
    title: string;
    subtitle: string;
    preview: string;
    configuration: string;
    meterTitle: string;
    meterSkin: string;
    theme: string;
    light: string;
    dark: string;
    language: string;
    scoreValue: string;
    maxScore: string;
    backgroundColor: string;
    ratingRanges: string;
    addRange: string;
    label: string;
    min: string;
    max: string;
    replayAnimation: string;
    export: string;
    exportButton: string;
    exporting: string;
    processing: string;
    transparent: string;
    exportInfo: string;
    low: string;
    medium: string;
    high: string;
    // Advanced customization labels
    needleType: string;
    centerIcon: string;
    fontFamily: string;
    fontSize: string;
    fontEffect: string;
    needleColor: string;
    advancedSettings: string;
    meterShape: string;
}

export const translations: Record<Language, {
    name: string;
    flag: string;
    code: string;
    ui: TranslationUI;
}> = {
    en: {
        name: 'English',
        flag: '🇺🇸',
        code: 'us',
        ui: {
            title: 'Rating Meter Generator',
            subtitle: 'Create viral animated rating meters for TikTok, Instagram & YouTube Reviews. Free & No Watermark.',
            preview: 'Preview',
            configuration: 'Configuration',
            meterTitle: 'Meter Title',
            meterSkin: 'Meter Skin',
            theme: 'Theme',
            light: 'Light',
            dark: 'Dark',
            language: 'Language',
            scoreValue: 'Score Value',
            maxScore: 'Max Score',
            backgroundColor: 'Background Color',
            ratingRanges: 'Rating Ranges',
            addRange: 'Add Range',
            label: 'Label',
            min: 'Min',
            max: 'Max',
            replayAnimation: 'Replay Animation',
            export: 'Export',
            exportButton: 'Export',
            exporting: 'Exporting...',
            processing: 'Processing...',
            transparent: 'Transparent',
            exportInfo: 'Export creates a animation from 0 to target score.',
            low: 'Low',
            medium: 'Medium',
            high: 'High',
            needleType: 'Needle Type',
            centerIcon: 'Center Icon',
            fontFamily: 'Font Family',
            fontSize: 'Font Size',
            fontEffect: 'Font Effect',
            needleColor: 'Needle Color',
            advancedSettings: 'Advanced Settings',
            meterShape: 'Meter Shape',
        }
    },
    tr: {
        name: 'Türkçe',
        flag: '🇹🇷',
        code: 'tr',
        ui: {
            title: 'Derecelendirme Metresi Oluşturucu',
            subtitle: 'Derecelendirme metresi animasyonlarınızı oluşturun ve dışa aktarın.',
            preview: 'Önizleme',
            configuration: 'Yapılandırma',
            meterTitle: 'Metre Başlığı',
            meterSkin: 'Metre Görünümü',
            theme: 'Tema',
            light: 'Aydınlık',
            dark: 'Karanlık',
            language: 'Dil',
            scoreValue: 'Skor Değeri',
            maxScore: 'Maksimum Skor',
            backgroundColor: 'Arka Plan Rengi',
            ratingRanges: 'Derece Aralıkları',
            addRange: 'Aralık Ekle',
            label: 'Etiket',
            min: 'Min',
            max: 'Maks',
            replayAnimation: 'Animasyonu Yeniden Oynat',
            export: 'Dışa Aktar',
            exportButton: 'Dışa Aktar',
            exporting: 'Dışa aktarılıyor...',
            processing: 'İşleniyor...',
            transparent: 'Şeffaf',
            exportInfo: 'Dışa aktarma işlemi 0\'dan hedef skora bir animasyon oluşturur.',
            low: 'Düşük',
            medium: 'Orta',
            high: 'Yüksek',
            needleType: 'İbre Tipi',
            centerIcon: 'Merkez İkonu',
            fontFamily: 'Yazı Tipi',
            fontSize: 'Yazı Boyutu',
            fontEffect: 'Yazı Efekti',
            needleColor: 'İbre Rengi',
            advancedSettings: 'Gelişmiş Ayarlar',
            meterShape: 'Metre Şekli',
        }
    },
    zh: {
        name: '中文',
        flag: '🇨🇳',
        code: 'cn',
        ui: {
            title: '评分仪表生成器',
            subtitle: '创建、自定义并导出您的评分仪表动画。',
            preview: '预览',
            configuration: '配置',
            meterTitle: '仪表标题',
            meterSkin: '仪表皮肤',
            theme: '主题',
            light: '浅色',
            dark: '深色',
            language: '语言',
            scoreValue: '分数值',
            maxScore: '最大分数',
            backgroundColor: '背景颜色',
            ratingRanges: '评分范围',
            addRange: '添加范围',
            label: '标签',
            min: '最小',
            max: '最大',
            replayAnimation: '回放动画',
            export: '导出',
            exportButton: '导出',
            exporting: '导出中...',
            processing: '处理中...',
            transparent: '透明',
            exportInfo: '导出创建一个从0到目标分数的动画。',
            low: '低',
            medium: '中',
            high: '高',
            needleType: '指针类型',
            centerIcon: '中心图标',
            fontFamily: '字体库',
            fontSize: '字体大小',
            fontEffect: '字体效果',
            needleColor: '指针颜色',
            advancedSettings: '高级设置',
            meterShape: '仪表形状',
        }
    },
    hi: {
        name: 'हिन्दी',
        flag: '🇮🇳',
        code: 'in',
        ui: {
            title: 'रेटिंग मीटर जेनरेटर',
            subtitle: 'अपने रेटिंग मीटर एनिमेशन बनाएं, कस्टमाइज़ करें और निर्यात करें।',
            preview: 'पूर्वावलोकन',
            configuration: 'कॉन्फ़िगरेशन',
            meterTitle: 'मीटर शीर्षक',
            meterSkin: 'मीटर स्किन',
            theme: 'थीम',
            light: 'लाइट',
            dark: 'डार्क',
            language: 'भाषा',
            scoreValue: 'स्कोर मान',
            maxScore: 'अधिकतम स्कोर',
            backgroundColor: 'पृष्ठभूमि का रंग',
            ratingRanges: 'रेटिंग रेंज',
            addRange: 'रेंज जोड़ें',
            label: 'लेबल',
            min: 'न्यूनतम',
            max: 'अधिकतम',
            replayAnimation: 'एनिमेशन फिर से चलाएँ',
            export: 'निर्यात करें',
            exportButton: 'निर्यात',
            exporting: 'निर्यात किया जा रहा है...',
            processing: 'प्रसंस्करण...',
            transparent: 'पारदर्शी',
            exportInfo: 'निर्यात 0 से लक्ष्य स्कोर तक एक एनिमेशन बनाता है।',
            low: 'कम',
            medium: 'मध्यम',
            high: 'उच्च',
            needleType: 'सुई का प्रकार',
            centerIcon: 'केंद्र आइकन',
            fontFamily: 'फ़ॉन्ट परिवार',
            fontSize: 'फ़ॉन्ट आकार',
            fontEffect: 'फ़ॉन्ट प्रभाव',
            needleColor: 'सुई का रंग',
            advancedSettings: 'उन्नत सेटिंग्स',
            meterShape: 'मीटर आकार',
        }
    },
    es: {
        name: 'Español',
        flag: '🇪🇸',
        code: 'es',
        ui: {
            title: 'Generador de Medidor',
            subtitle: 'Crea, personaliza y exporta tus animaciones de medidor.',
            preview: 'Vista previa',
            configuration: 'Configuración',
            meterTitle: 'Título del Medidor',
            meterSkin: 'Skin del Medidor',
            theme: 'Tema',
            light: 'Claro',
            dark: 'Oscuro',
            language: 'Idioma',
            scoreValue: 'Valor del Puntaje',
            maxScore: 'Puntaje Máximo',
            backgroundColor: 'Color de Fondo',
            ratingRanges: 'Rangos de Calificación',
            addRange: 'Agregar Rango',
            label: 'Etiqueta',
            min: 'Mín.',
            max: 'Máx.',
            replayAnimation: 'Repetir animación',
            export: 'Exportar',
            exportButton: 'Exportar',
            exporting: 'Exportando...',
            processing: 'Procesando...',
            transparent: 'Transparente',
            exportInfo: 'La exportación crea una animación de 0 al puntaje objetivo.',
            low: 'Bajo',
            medium: 'Medio',
            high: 'Alto',
            needleType: 'Tipo de Aguja',
            centerIcon: 'Icono Central',
            fontFamily: 'Familia de Fuente',
            fontSize: 'Tamaño de Fuente',
            fontEffect: 'Efecto de Fuente',
            needleColor: 'Color de Aguja',
            advancedSettings: 'Ajustes Avanzados',
            meterShape: 'Forma del Medidor',
        }
    },
    ar: {
        name: 'العربية',
        flag: '🇸🇦',
        code: 'sa',
        ui: {
            title: 'مولد مقياس التقييم',
            subtitle: 'قم بإنشاء وتخصيص وتصدير رسوم مقياس التقييم المتحركة الخاصة بك.',
            preview: 'معاينة',
            configuration: 'التكوين',
            meterTitle: 'عنوان المقياس',
            meterSkin: 'مظهر المقياس',
            theme: 'المظهر',
            light: 'فاتح',
            dark: 'داكن',
            language: 'اللغة',
            scoreValue: 'قيمة النتيجة',
            maxScore: 'أقصى نتيجة',
            backgroundColor: 'لون الخلفية',
            ratingRanges: 'نطاقات التقييم',
            addRange: 'إضافة نطاق',
            label: 'ملصق',
            min: 'أدنى',
            max: 'أقصى',
            replayAnimation: 'إعادة الرسوم المتحركة',
            export: 'تصدير',
            exportButton: 'تصدير',
            exporting: 'جاري التصدير...',
            processing: 'جاري المعالجة...',
            transparent: 'شفاف',
            exportInfo: 'يؤدي التصدير إلى إنشاء رسوم متحركة من 0 إلى النتيجة المستهدفة.',
            low: 'منخفض',
            medium: 'متوسط',
            high: 'مرتفع',
            needleType: 'نوع الإبرة',
            centerIcon: 'أيقونة المركز',
            fontFamily: 'عائلة الخط',
            fontSize: 'حجم الخط',
            fontEffect: 'تأثير الخط',
            needleColor: 'لون الإبرة',
            advancedSettings: 'إعدادات متقدمة',
            meterShape: 'شكل المقياس',
        }
    },
    bn: {
        name: 'বাংলা',
        flag: '🇧🇩',
        code: 'bd',
        ui: {
            title: 'রেটিং মিটার জেনারেটর',
            subtitle: 'আপনার রেটিং মিটার অ্যানিমেশন তৈরি করুন, কাস্টমাইজ করুন এবং রপ্তানি করুন।',
            preview: 'প্রিভিউ',
            configuration: 'কনফিগারেশন',
            meterTitle: 'মিটার শিরোনাম',
            meterSkin: 'মিটার স্কিন',
            theme: 'থিম',
            light: 'লাইট',
            dark: 'ডার্ক',
            language: 'ভাষা',
            scoreValue: 'স্কোর ভ্যালু',
            maxScore: 'সর্বোচ্চ স্কোর',
            backgroundColor: 'ব্যাকগ্রাউন্ড কালার',
            ratingRanges: 'রেটিং রেঞ্জ',
            addRange: 'রেঞ্জ যোগ করুন',
            label: 'লেবেল',
            min: 'সর্বনিম্ন',
            max: 'সর্বোচ্চ',
            replayAnimation: 'অ্যানিমেশন রিপ্লে',
            export: 'রপ্তানি করুন',
            exportButton: 'রপ্তানি',
            exporting: 'রপ্তানি হচ্ছে...',
            processing: 'প্রক্রিয়াকরণ...',
            transparent: 'স্বচ্ছ',
            exportInfo: 'রপ্তানি ০ থেকে লক্ষ্য স্কোর পর্যন্ত একটি অ্যানিমেশন তৈরি করে।',
            low: 'কম',
            medium: 'মাঝারি',
            high: 'বেশি',
            needleType: 'নিডল টাইপ',
            centerIcon: 'সেন্টার আইকন',
            fontFamily: 'ফন্ট ফ্যামিলি',
            fontSize: 'ফন্ট সাইজ',
            fontEffect: 'ফন্ট ইফেক্ট',
            needleColor: 'নিডল কালার',
            advancedSettings: 'উন্নত সেটিংস',
            meterShape: 'মিটার শেপ',
        }
    },
    pt: {
        name: 'Português',
        flag: '🇵🇹',
        code: 'br',
        ui: {
            title: 'Gerador de Medidores',
            subtitle: 'Crie, personalize e exporte as suas animações de medidores.',
            preview: 'Visualização',
            configuration: 'Configuração',
            meterTitle: 'Título do Medidor',
            meterSkin: 'Pele do Medidor',
            theme: 'Tema',
            light: 'Claro',
            dark: 'Escuro',
            language: 'Idioma',
            scoreValue: 'Valor da Pontuação',
            maxScore: 'Pontuação Máxima',
            backgroundColor: 'Cor de Fundo',
            ratingRanges: 'Intervalos de Classificação',
            addRange: 'Adicionar Intervalo',
            label: 'Rótulo',
            min: 'Mín.',
            max: 'Máx.',
            replayAnimation: 'Reproduzir animação',
            export: 'Exportar',
            exportButton: 'Exportar',
            exporting: 'Exportando...',
            processing: 'Processando...',
            transparent: 'Transparente',
            exportInfo: 'A exportação cria uma animação de 0 até a pontuação alvo.',
            low: 'Baixo',
            medium: 'Médio',
            high: 'Alto',
            needleType: 'Tipo de Agulha',
            centerIcon: 'Ícone Central',
            fontFamily: 'Família de Fonte',
            fontSize: 'Tamanho da Fonte',
            fontEffect: 'Efeito de Fonte',
            needleColor: 'Cor da Agulha',
            advancedSettings: 'Ajustes Avançados',
            meterShape: 'Forma do Medidor',
        }
    },
    ru: {
        name: 'Русский',
        flag: '🇷🇺',
        code: 'ru',
        ui: {
            title: 'Генератор шкал',
            subtitle: 'Создавайте, настраивайте и экспортируйте анимацию шкал.',
            preview: 'Предпросмотр',
            configuration: 'Конфигурация',
            meterTitle: 'Заголовок шкалы',
            meterSkin: 'Скин шкалы',
            theme: 'Тема',
            light: 'Светлая',
            dark: 'Темная',
            language: 'Язык',
            scoreValue: 'Значение счета',
            maxScore: 'Макс. счет',
            backgroundColor: 'Цвет фона',
            ratingRanges: 'Диапазоны рейтинга',
            addRange: 'Добавить диапазон',
            label: 'Метка',
            min: 'Мин.',
            max: 'Макс.',
            replayAnimation: 'Повторить анимацию',
            export: 'Экспорт',
            exportButton: 'Экспорт',
            exporting: 'Экспорт...',
            processing: 'Обработка...',
            transparent: 'Прозрачный',
            exportInfo: 'Экспорт создает анимацию от 0 до целевого счета.',
            low: 'Низкий',
            medium: 'Средний',
            high: 'Высокий',
            needleType: 'Тип стрелки',
            centerIcon: 'Центральная иконка',
            fontFamily: 'Семейство шрифтов',
            fontSize: 'Размер шрифта',
            fontEffect: 'Эффект шрифта',
            needleColor: 'Цвет стрелки',
            advancedSettings: 'Расширенные настройки',
            meterShape: 'Форма шкалы',
        }
    },
    ja: {
        name: '日本語',
        flag: '🇯🇵',
        code: 'jp',
        ui: {
            title: '評価メータージェネレーター',
            subtitle: '評価メーターのアニメーションを作成、カスタマイズ、エクスポートします。',
            preview: 'プレビュー',
            configuration: '配置',
            meterTitle: 'メーターのタイトル',
            meterSkin: 'メータースキン',
            theme: 'テーマ',
            light: 'ライト',
            dark: 'ダーク',
            language: '言語',
            scoreValue: 'スコア値',
            maxScore: '最大スコア',
            backgroundColor: '背景色',
            ratingRanges: '評価範囲',
            addRange: '範囲を追加',
            label: 'ラベル',
            min: '最小',
            max: '最大',
            replayAnimation: 'アニメーション再生',
            export: 'エクスポート',
            exportButton: 'エクスポート',
            exporting: 'エクスポート中...',
            processing: '処理中...',
            transparent: '透明',
            exportInfo: 'エクスポートは 0 から目標スコアまでのアニメーションを作成します。',
            low: '低い',
            medium: '中',
            high: '高い',
            needleType: '針のタイプ',
            centerIcon: 'センターアイコン',
            fontFamily: 'フォントファミリー',
            fontSize: 'フォントサイズ',
            fontEffect: 'フォント効果',
            needleColor: '針の色',
            advancedSettings: '詳細設定',
            meterShape: 'メーターの形状',
        }
    },
    fr: {
        name: 'Français',
        flag: '🇫🇷',
        code: 'fr',
        ui: {
            title: 'Générateur de jauge',
            subtitle: 'Créez, personnalisez et exportez vos animations de jauge.',
            preview: 'Aperçu',
            configuration: 'Configuration',
            meterTitle: 'Titre de la jauge',
            meterSkin: 'Peau de la jauge',
            theme: 'Thème',
            light: 'Clair',
            dark: 'Sombre',
            language: 'Langue',
            scoreValue: 'Valeur du score',
            maxScore: 'Score maximum',
            backgroundColor: 'Couleur de fond',
            ratingRanges: 'Plages d\'évaluation',
            addRange: 'Ajouter une plage',
            label: 'Étiquette',
            min: 'Min',
            max: 'Max',
            replayAnimation: 'Rejouer l\'animation',
            export: 'Exporter',
            exportButton: 'Exporter',
            exporting: 'Exportation...',
            processing: 'Traitement...',
            transparent: 'Transparent',
            exportInfo: 'L\'exportation crée une animation de 0 au score cible.',
            low: 'Bas',
            medium: 'Moyen',
            high: 'Haut',
            needleType: 'Type d\'aiguille',
            centerIcon: 'Icône centrale',
            fontFamily: 'Famille de polices',
            fontSize: 'Taille de police',
            fontEffect: 'Effet de police',
            needleColor: 'Couleur de l\'aiguille',
            advancedSettings: 'Paramètres avancés',
            meterShape: 'Forme de la jauge',
        }
    },
    de: {
        name: 'Deutsch',
        flag: '🇩🇪',
        code: 'de',
        ui: {
            title: 'Bewertungsmesser-Generator',
            subtitle: 'Bewertungsmesser-Animationen erstellen, anpassen und exportieren.',
            preview: 'Vorschau',
            configuration: 'Konfiguration',
            meterTitle: 'Metertitel',
            meterSkin: 'Meter-Skin',
            theme: 'Thema',
            light: 'Hell',
            dark: 'Dunkel',
            language: 'Sprache',
            scoreValue: 'Punktwert',
            maxScore: 'Maximalpunktzahl',
            backgroundColor: 'Hintergrundfarbe',
            ratingRanges: 'Bewertungsbereiche',
            addRange: 'Bereich hinzufügen',
            label: 'Beschriftung',
            min: 'Minimum',
            max: 'Maximum',
            replayAnimation: 'Animation wiederholen',
            export: 'Exportieren',
            exportButton: 'Exportieren',
            exporting: 'Exportieren...',
            processing: 'Verarbeitung...',
            transparent: 'Transparent',
            exportInfo: 'Export erstellt eine Animation von 0 bis zum Zielwert.',
            low: 'Niedrig',
            medium: 'Mittel',
            high: 'Hoch',
            needleType: 'Nadeltyp',
            centerIcon: 'Mittel-Icon',
            fontFamily: 'Schriftfamilie',
            fontSize: 'Schriftgröße',
            fontEffect: 'Schrifteffekt',
            needleColor: 'Nadelfarbe',
            advancedSettings: 'Erweiterte Einstellungen',
            meterShape: 'Meterform',
        }
    },
    ko: {
        name: '한국어',
        flag: '🇰🇷',
        code: 'kr',
        ui: {
            title: '평가 미터 생성기',
            subtitle: '평가 미터 애니메이션을 생성, 사용자 지정 및 내보냅니다.',
            preview: '미리보기',
            configuration: '배치',
            meterTitle: '미터 제목',
            meterSkin: '미터 스킨',
            theme: '테마',
            light: '라이트',
            dark: '다크',
            language: '언어',
            scoreValue: '점수 값',
            maxScore: '최고 점수',
            backgroundColor: '배경 색상',
            ratingRanges: '평가 범위',
            addRange: '범위 추가',
            label: '라벨',
            min: '최소',
            max: '최고',
            replayAnimation: '애니메이션 재생',
            export: '내보내기',
            exportButton: '내보내기',
            exporting: '내보내는 중...',
            processing: '처리 중...',
            transparent: '투명한',
            exportInfo: '내보내기는 0에서 목표 점수까지의 애니메이션을 만듭니다.',
            low: '낮음',
            medium: '중간',
            high: '높음',
            needleType: '바늘 유형',
            centerIcon: '중앙 아이콘',
            fontFamily: '글꼴 패밀리',
            fontSize: '글꼴 크기',
            fontEffect: '글꼴 효과',
            needleColor: '바늘 색상',
            advancedSettings: '고급 설정',
            meterShape: '미터 모양',
        }
    },
    vi: {
        name: 'Tiếng Việt',
        flag: '🇻🇳',
        code: 'vn',
        ui: {
            title: 'Trình tạo máy đo xếp hạng',
            subtitle: 'Tạo, tùy chỉnh và xuất các hoạt ảnh máy đo xếp hạng của bạn.',
            preview: 'Xem trước',
            configuration: 'Cấu hình',
            meterTitle: 'Tiêu đề máy đo',
            meterSkin: 'Giao diện máy đo',
            theme: 'Chủ đề',
            light: 'Sáng',
            dark: 'Tối',
            language: 'Ngôn ngữ',
            scoreValue: 'Giá trị điểm',
            maxScore: 'Điểm tối đa',
            backgroundColor: 'Màu nền',
            ratingRanges: 'Phạm vi xếp hạng',
            addRange: 'Thêm phạm vi',
            label: 'Nhãn',
            min: 'Tối thiểu',
            max: 'Tối đa',
            replayAnimation: 'Phát lại hoạt ảnh',
            export: 'Xuất',
            exportButton: 'Xuất',
            exporting: 'Đang xuất...',
            processing: 'Đang xử lý...',
            transparent: 'Trong suốt',
            exportInfo: 'Xuất tạo một hoạt ảnh từ 0 đến điểm mục tiêu.',
            low: 'Thấp',
            medium: 'Trung bình',
            high: 'Cao',
            needleType: 'Loại kim',
            centerIcon: 'Biểu tượng trung tâm',
            fontFamily: 'Bộ phông chữ',
            fontSize: 'Kích thước phông chữ',
            fontEffect: 'Hiệu ứng phông chữ',
            needleColor: 'Màu kim',
            advancedSettings: 'Cài đặt nâng cao',
            meterShape: 'Hình dạng máy đo',
        }
    },
    it: {
        name: 'Italiano',
        flag: '🇮🇹',
        code: 'it',
        ui: {
            title: 'Generatore di misuratori',
            subtitle: 'Crea, personalizza ed esporta le animazioni del tuo misuratore.',
            preview: 'Anteprima',
            configuration: 'Configurazione',
            meterTitle: 'Titolo del misuratore',
            meterSkin: 'Skin del misuratore',
            theme: 'Tema',
            light: 'Chiaro',
            dark: 'Scuro',
            language: 'Lingua',
            scoreValue: 'Valore del punteggio',
            maxScore: 'Punteggio massimo',
            backgroundColor: 'Colore di sfondo',
            ratingRanges: 'Intervalli di valutazione',
            addRange: 'Aggiungi intervallo',
            label: 'Etichetta',
            min: 'Minimo',
            max: 'Massimo',
            replayAnimation: 'Riproduci animazione',
            export: 'Esporta',
            exportButton: 'Esporta',
            exporting: 'Esportazione...',
            processing: 'Elaborazione...',
            transparent: 'Trasparente',
            exportInfo: 'L\'esportazione crea un\'animazione da 0 al punteggio target.',
            low: 'Basso',
            medium: 'Medio',
            high: 'Alto',
            needleType: 'Tipo di ago',
            centerIcon: 'Icona centrale',
            fontFamily: 'Famiglia di caratteri',
            fontSize: 'Dimensione del carattere',
            fontEffect: 'Effetto carattere',
            needleColor: 'Colore dell\'ago',
            advancedSettings: 'Impostazioni avanzate',
            meterShape: 'Forma del misuratore',
        }
    },
    fa: {
        name: 'فارسی',
        flag: '🇮🇷',
        code: 'ir',
        ui: {
            title: 'مولد درجه بندی',
            subtitle: 'انیمیشن‌های متر رتبه‌بندی خود را ایجاد، سفارشی و صادر کنید.',
            preview: 'پیش‌نمایش',
            configuration: 'پیکربندی',
            meterTitle: 'عنوان متر',
            meterSkin: 'ظاهر متر',
            theme: 'تم',
            light: 'روشن',
            dark: 'تاریک',
            language: 'زبان',
            scoreValue: 'مقدار امتیاز',
            maxScore: 'حداکثر امتیاز',
            backgroundColor: 'رنگ پس‌زمینه',
            ratingRanges: 'محدوده‌های رتبه‌بندی',
            addRange: 'افزودن محدوده',
            label: 'برچسب',
            min: 'حداقل',
            max: 'بیشترین',
            replayAnimation: 'پخش مجدد انیمیشن',
            export: 'خروجی گرفتن',
            exportButton: 'خروجی',
            exporting: 'در حال خروجی گرفتن...',
            processing: 'در حال پردازش...',
            transparent: 'شفاف',
            exportInfo: 'خروجی گرفتن یک انیمیشن از 0 تا امتیاز هدف ایجاد می کند.',
            low: 'کم',
            medium: 'متوسط',
            high: 'زیاد',
            needleType: 'نوع سوزن',
            centerIcon: 'آیکون مرکز',
            fontFamily: 'خانواده فونت',
            fontSize: 'اندازه فونت',
            fontEffect: 'افکت فونت',
            needleColor: 'رنگ سوزن',
            advancedSettings: 'تنظیمات پیشرفته',
            meterShape: 'شکل متر',
        }
    },
    pl: {
        name: 'Polski',
        flag: '🇵🇱',
        code: 'pl',
        ui: {
            title: 'Generator miernika',
            subtitle: 'Twórz, dostosowuj i eksportuj animacje miernika ocen.',
            preview: 'Podgląd',
            configuration: 'Konfiguracja',
            meterTitle: 'Tytuł miernika',
            meterSkin: 'Skórka miernika',
            theme: 'Motyw',
            light: 'Jasny',
            dark: 'Ciemny',
            language: 'Język',
            scoreValue: 'Wartość wyniku',
            maxScore: 'Maksymalny wynik',
            backgroundColor: 'Kolor tła',
            ratingRanges: 'Zakresy ocen',
            addRange: 'Dodaj zakres',
            label: 'Etykieta',
            min: 'Minimum',
            max: 'Maksymalny',
            replayAnimation: 'Odtwórz animację',
            export: 'Eksportuj',
            exportButton: 'Eksportuj',
            exporting: 'Eksportowanie...',
            processing: 'Przetwarzanie...',
            transparent: 'Przezroczysty',
            exportInfo: 'Eksport tworzy animację od 0 do wyniku docelowego.',
            low: 'Niski',
            medium: 'Średni',
            high: 'Wysoki',
            needleType: 'Typ wskazówki',
            centerIcon: 'Ikona centralna',
            fontFamily: 'Rodzina czcionek',
            fontSize: 'Rozmiar czcionki',
            fontEffect: 'Efekt czcionki',
            needleColor: 'Kolor wskazówki',
            advancedSettings: 'Ustawienia zaawansowane',
            meterShape: 'Kształt miernika',
        }
    },
    uk: {
        name: 'Українська',
        flag: '🇺🇦',
        code: 'ua',
        ui: {
            title: 'Генератор рейтингу',
            subtitle: 'Створюйте, налаштовуйте та експортуйте анімації рейтингу.',
            preview: 'Попередній перегляд',
            configuration: 'Конфігурація',
            meterTitle: 'Заголовок',
            meterSkin: 'Скін',
            theme: 'Тема',
            light: 'Світла',
            dark: 'Темна',
            language: 'Мова',
            scoreValue: 'Значення',
            maxScore: 'Максимум',
            backgroundColor: 'Колір фону',
            ratingRanges: 'Діапазони',
            addRange: 'Додати',
            label: 'Мітка',
            min: 'Мінімум',
            max: 'Максимум',
            replayAnimation: 'Відтворити анімацію',
            export: 'Експорт',
            exportButton: 'Експорт',
            exporting: 'Експорт...',
            processing: 'Обробка...',
            transparent: 'Прозорий',
            exportInfo: 'Експорт створює анімацію від 0 до цільового результату.',
            low: 'Низький',
            medium: 'Середній',
            high: 'Високий',
            needleType: 'Тип стрілки',
            centerIcon: 'Центральна іконка',
            fontFamily: 'Шрифт',
            fontSize: 'Розмір шрифту',
            fontEffect: 'Ефект шрифту',
            needleColor: 'Колір стрілки',
            advancedSettings: 'Розширені налаштування',
            meterShape: 'Форма шкали',
        }
    },
    nl: {
        name: 'Nederlands',
        flag: '🇳🇱',
        code: 'nl',
        ui: {
            title: 'Beoordelingsmeter',
            subtitle: 'Maak, pas aan en exporteer je beoordelingsmeter animaties.',
            preview: 'Voorbeeld',
            configuration: 'Configuratie',
            meterTitle: 'Metertitel',
            meterSkin: 'Meter Skin',
            theme: 'Thema',
            light: 'Licht',
            dark: 'Donker',
            language: 'Taal',
            scoreValue: 'Scorewaarde',
            maxScore: 'Maximaal',
            backgroundColor: 'Achtergrondkleur',
            ratingRanges: 'Beoordelingsbereiken',
            addRange: 'Bereik Toevoegen',
            label: 'Label',
            min: 'Minimum',
            max: 'Maximaal',
            replayAnimation: 'Animatie opnieuw afspelen',
            export: 'Exporteren',
            exportButton: 'Exporteren',
            exporting: 'Exporteren...',
            processing: 'Verwerking...',
            transparent: 'Transparant',
            exportInfo: 'Export maakt een animatie van 0 tot de doelscore.',
            low: 'Laag',
            medium: 'Gemiddeld',
            high: 'Hoog',
            needleType: 'Naaldtype',
            centerIcon: 'Centraal Pictogram',
            fontFamily: 'Lettertype',
            fontSize: 'Lettergrootte',
            fontEffect: 'Teksteffect',
            needleColor: 'Naaldkleur',
            advancedSettings: 'Geavanceerde Instellingen',
            meterShape: 'Meter vorm',
        }
    },
    th: {
        name: 'ไทย',
        flag: '🇹🇭',
        code: 'th',
        ui: {
            title: 'ตัวสร้างมิเตอร์เรตติ้ง',
            subtitle: 'สร้าง ปรับแต่ง และส่งออกแอนิเมชั่นมิเตอร์เรตติ้งของคุณ',
            preview: 'ดูตัวอย่าง',
            configuration: 'การกำหนดค่า',
            meterTitle: 'ชื่อมิเตอร์',
            meterSkin: 'สกินมิเตอร์',
            theme: 'ธีม',
            light: 'สว่าง',
            dark: 'มืด',
            language: 'ภาษา',
            scoreValue: 'ค่าคะแนน',
            maxScore: 'สูงสุด',
            backgroundColor: 'สีพื้นหลัง',
            ratingRanges: 'ช่วงระดับ',
            addRange: 'เพิ่มช่วง',
            label: 'ป้าย',
            min: 'ต่ำสุด',
            max: 'สูงสุด',
            replayAnimation: 'เล่นซ้ำแอนิเมชัน',
            export: 'ส่งออก',
            exportButton: 'ส่งออก',
            exporting: 'กำลังส่งออก...',
            processing: 'การประมวลผล...',
            transparent: 'โปร่งใส',
            exportInfo: 'การส่งออกจะสร้างแอนิเมชั่นจาก 0 ไปยังคะแนนเป้าหมาย',
            low: 'ต่ำ',
            medium: 'ปานกลาง',
            high: 'สูง',
            needleType: 'ประเภทเข็ม',
            centerIcon: 'ไอคอนตรงกลาง',
            fontFamily: 'ตระกูลอักษร',
            fontSize: 'ขนาดตัวอักษร',
            fontEffect: 'เอฟเฟกต์ตัวอักษร',
            needleColor: 'สีเข็ม',
            advancedSettings: 'การตั้งค่าขั้นสูง',
            meterShape: 'รูปร่างมิเตอร์',
        }
    }
};
